apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-stack
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-stack
  template:
    metadata:
      labels:
        app: redis-stack
    spec:
      containers:
      - name: redis
        image: redis:6.2-alpine
        command: ["redis-server"]
        args: ["--appendonly yes", "--enable-module-rdb"]
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: 512Mi
            cpu: 100m
          requests:
            memory: 256Mi
            cpu: 50m
      - name: redis-insight
        image: redislabs/redisinsight
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 256Mi
            cpu: 50m
          requests:
            memory: 128Mi
            cpu: 25m
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            weight: 100
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80

