

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-stack
spec:
  selector:
    matchLabels:
      app: redis-stack
  template:
    metadata:
      labels:
        app: redis-stack
    spec:
      containers:
        - name: redis-stack
          image: docker.io/redis/redis-stack:latest
          ports:
            - containerPort: 6379
              name: redis-stack
            - containerPort: 8001
              name: redisinsight
          volumeMounts:
            - name: redis-persistent-storage
              mountPath: /data
      volumes:
      - name: redis-persistent-storage

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "redis-stack-service"
  namespace: "default"
spec:
  ports:
  - name: "6379-to-6379-tcp"
    protocol: "TCP"
    port: 6379
    targetPort: 6379
  - name: "8001-to-8001-tcp"
    protocol: "TCP"
    port: 8001
    targetPort: 8001
  selector:
    app: "redis-stack"
  type: "ClusterIP"

