# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.2.0

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.TTY/redis-stack: "false"
    io.podman.annotations.autoremove/redis-stack: "FALSE"
    io.podman.annotations.init/redis-stack: "FALSE"
    io.podman.annotations.privileged/redis-stack: "FALSE"
    io.podman.annotations.publish-all/redis-stack: "FALSE"
  creationTimestamp: "2022-10-04T20:03:20Z"
  labels:
    app: redis-stack-pod
  name: redis-stack-pod
spec:
  containers:
  - image: docker.io/redis/redis-stack:latest
    name: redis-stack
    ports:
    - containerPort: 6379
      hostPort: 6379
    - containerPort: 8001
      hostPort: 8001
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /data
      name: local-data-pvc
  volumes:
  - name: local-data-pvc
    persistentVolumeClaim:
      claimName: local-data

